### ISSUE TITLE
Aggiornamento lista browsers

### ISSUE THREAD

**Issue by francescozaia** [italia/browserslist-config-design-italia#2]
Ciao!

Volevo segnalare che il [paragrafo di riferimento delle linee guida](https://docs.italia.it/italia/designers-italia/design-linee-guida-docs/it/2020.1/doc/user-interface/lo-sviluppo-di-un-interfaccia-e-i-web-kit.html#strumenti) mostra una lista di browser stilata ad inizio 2020, ma il metro di misura fondamentale è definito prima e dice:

> "è necessario assicurare la compatibilità con versioni dei browser che abbiano una penetrazione media tra la popolazione di almeno **1 persona ogni 100 abitanti**"

Ad oggi, scaricando il csv con le statistiche italiane da StatCounter (attraverso il link presente nelle linee guida stesse), si può vedere come  ad esempio **in tutti i mesi del 2021 l'utilizzo IE11 sia sotto l'1%**, rendendone a mio avviso non obbligatorio il supporto e quindi la sua presenza nel configuratore. Così come, probabilmente, anche versioni minori di browser mobili.

Insomma, la lista di browser presente nelle linee guida non deve essere vista come un obbligo. Lo segnalo in particolare perché ci si possa ragionare un po' e valutare un supporto adeguato per lo sviluppo futuro di Bootstrap Italia.

**Comment by dej611** [comment]
Mi sembra una giusta riflessione.
Si potrebbe cambiare la lista con la seguente query:

```
>= 1% in IT
```

Al momento il risultato di questa query è il seguente:

```
["and_chr 96", "chrome 96", "edge 96", "firefox 95", "firefox 94", "ios_saf 15.0-15.1", "ios_saf 14.5-14.8", “safari 15.1”, “safari 14.1”]
```

Detto ciò, forse proporrei di scendere anche un poco sotto l’1% di copertura, magari andando sullo 0.5%:

```
>= 0.5% in IT
```

Per incontrare IE11 dalle prove che ho fatto bisogna scendere ancora più sotto dello 0.5%.

**Comment by bfabio** [comment]
Il [Manuale operativo di Design](https://manuale-operativo-design-docs.vercel.app/doc/esperienza-utente/lo-sviluppo-della-interfaccia-utente.html) in arrivo non ha più la lista dei browser, ma il consiglio di usare `italia/browserslist-config-design-italia` :tada: 

`>= 1% in IT` mi sembra buono, la differenza con `0.5% in IT` ora è sostanzialmente Safari 14 (AKA, il nuovo Explorer)

cc @danielaiozzo

**Comment by Fupete** [comment]
cc @ruphy ⬆️
